# Generated by Django 5.1 on 2024-09-20 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='city',
        ),
        migrations.AddField(
            model_name='advert',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advert',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_adverts', to='advert.city'),
        ),
        migrations.AddField(
            model_name='advert',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_adverts', to='advert.city'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
